name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
        #adding new step for uploading artifacts
      - name: Uploading Job Artifacts
        uses: actions/upload-artifact@v3 #this action is used to upload the artifacts into archieve and in with we are providing some configurations
        with:
          name: dist-files #the name of the folder either will be build or dist-file, it is upto you
          #path: | #adding pipe symbol here to add the multiple file in artifacts path
           # dist 
            #package.json
          path:
            dist #another way of adding the path
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      #steps to add deploying the artifacts into the web-server
      - name: Downloading Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files #using same name as uploading build artifacts, it will grab the zip file from the build upload artifacts, downloaded and unzipped over here
      - name: Ouptut Contents   #to view the output of the dist-file folder
        run: ls
      - name: Deploy
        run: echo "Deploying..."
